[functions.zelle-payment]
verify_jwt = false

[functions.create-stripe-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-customer-portal-account]
verify_jwt = false
