import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')??'', ANON=Deno.env.get('SUPABASE_ANON_KEY')??'', SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'';
const SITE=(Deno.env.get('SITE_URL')??Deno.env.get('APP_URL')??'https://pepscriptrx.vercel.app').replace(/\/+$/,'');
const headers={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Content-Type':'application/json'};

serve(async(req)=>{if(req.method==='OPTIONS')return response({},200);if(req.method!=='POST')return response({error:'Method not allowed'},405);
  const origin=req.headers.get('origin')??'';if(!allowedOrigin(origin))return response({error:'Application origin is not allowed'},403);
  const db=createClient(URL,SERVICE);const applicantAuth=createClient(URL,ANON);let createdUserId='';let applicationId='';
  try{const body=await req.json();validate(body);const email=clean(body.email).toLowerCase();
    const {data:existing}=await db.from('rep_store_intake_submissions').select('id,approval_status').eq('source_portal_id','aactivated').ilike('email',email).maybeSingle();
    if(existing)return response({error:'An AACTIVATEDRX application already exists for this email. Sign in to view its status.'},409);
    const redirectTo=`${SITE}/auth/callback`;const {data:userResult,error:userError}=await applicantAuth.auth.signUp({email,password:String(body.password),options:{emailRedirectTo:redirectTo,data:{full_name:`${clean(body.first_name)} ${clean(body.last_name)}`,role:'rep_applicant',brand_id:'aactivated'}}});if(userError||!userResult.user)throw userError??new Error('Account creation failed');createdUserId=userResult.user.id;
    const now=new Date().toISOString();const fullName=`${clean(body.first_name)} ${clean(body.last_name)}`;
    const {error:profileError}=await db.from('profiles').upsert({id:createdUserId,auth_user_id:createdUserId,email,full_name:fullName,role:'rep_applicant',brand_id:'aactivated',store_slug:'aactivated'},{onConflict:'id'});if(profileError)throw profileError;
    const {data:application,error:applicationError}=await db.from('rep_store_intake_submissions').insert({status:'new',approval_status:'pending',applicant_user_id:createdUserId,full_name:fullName,first_name:clean(body.first_name),last_name:clean(body.last_name),email,phone:clean(body.phone),city:clean(body.city),state:clean(body.state),social_profile:optional(body.social_profile),referral_rep:optional(body.referral_rep),parent_rep_or_admin_name:optional(body.referral_rep)??'AACTIVATEDRX',discovery_source:clean(body.discovery_source),motivation:clean(body.motivation),application_terms_accepted_at:now,privacy_accepted_at:now,selected_products:[],custom_products:[],store_type:'Rep under another admin / parent account',store_brand_name:`${fullName} — AACTIVATEDRX Rep Application`,source_portal_id:'aactivated',source_portal:'AACTIVATEDRX',source_route:'/aactivated/apply',parent_store_slug:'aactivated',parent_store_name:'AACTIVATEDRX',partner_admin_email:'guy@aactivated.com',approval_owner_email:'guy@aactivated.com',review_queue:'aactivated',review_admin_code:'GUY60',review_admin_name:'AACTIVATEDRX Administration',internal_notes:'Authenticated AACTIVATEDRX applicant account. Representative capabilities remain disabled pending approval.'}).select('id').single();if(applicationError)throw applicationError;applicationId=application.id;
    const {data:onboarding,error:onboardingError}=await db.from('aactivated_onboarding_profiles').insert({application_id:applicationId,user_id:createdUserId,state:'application_pending',account_status:'pending',commissions_enabled:false,referral_enabled:false}).select('id').single();if(onboardingError)throw onboardingError;
    await db.from('aactivated_onboarding_audit').insert({onboarding_id:onboarding.id,actor_id:createdUserId,action:'application_submitted',metadata:{authenticated_applicant:true}});
    return response({ok:true},201);
  }catch(error){if(applicationId)await db.from('rep_store_intake_submissions').delete().eq('id',applicationId);if(createdUserId)await db.auth.admin.deleteUser(createdUserId);console.error('AACTIVATED application failed',error instanceof Error?error.message:'unknown');return response({error:'We could not create your application account. Please try again or contact support.'},400);}});

function validate(body:Record<string,unknown>){for(const key of ['first_name','last_name','email','phone','city','state','discovery_source','motivation','password'])if(!clean(body[key]))throw new Error('Required application information is missing');if(!body.consent)throw new Error('Consent is required');if(!/^\S+@\S+\.\S+$/.test(clean(body.email)))throw new Error('Email is invalid');if(String(body.password).length<10)throw new Error('Password must be at least 10 characters');}
function allowedOrigin(origin:string){if(!origin)return false;try{const url=new URL(origin);return url.hostname==='localhost'||url.hostname==='127.0.0.1'||url.hostname==='pepscriptrx.vercel.app'||url.hostname.endsWith('-manuel-rodriguezs-projects-f5946c44.vercel.app');}catch{return false;}}
const clean=(value:unknown)=>String(value??'').trim();const optional=(value:unknown)=>clean(value)||null;
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers});}
