import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const URL=Deno.env.get('SUPABASE_URL')??'', ANON=Deno.env.get('SUPABASE_ANON_KEY')??'', SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'';
const EMAIL_KEY=Deno.env.get('EMAIL_PROVIDER_API_KEY')??Deno.env.get('RESEND_API_KEY')??'',FROM_EMAIL=Deno.env.get('FROM_EMAIL')??Deno.env.get('NOTIFY_FROM')??'PepScriptRX <noreply@pepscriptrx.com>',SITE=(Deno.env.get('SITE_URL')??Deno.env.get('APP_URL')??'https://pepscriptrx.vercel.app').replace(/\/+$/,'');
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Content-Type':'application/json'};
serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{
  const token=req.headers.get('Authorization')??''; const auth=createClient(URL,ANON,{global:{headers:{Authorization:token}}}); const {data:{user}}=await auth.auth.getUser(); if(!user)return out({error:'Authentication required'},401);
  const db=createClient(URL,SERVICE); const {data:admin}=await db.from('profiles').select('id,role,brand_id,store_slug').or(`id.eq.${user.id},auth_user_id.eq.${user.id}`).maybeSingle();
  const platform=['admin','owner','platform_admin','master_admin','super_admin'].includes(admin?.role); const scoped=['rx_plus_admin','partner_admin_full'].includes(admin?.role)&&['aactivated','aactivatedrx'].includes(String(admin?.brand_id??admin?.store_slug).toLowerCase()); if(!platform&&!scoped)return out({error:'AACTIVATEDRX administrator authorization required'},403);
  const body=await req.json(); const {data:application}=await db.from('rep_store_intake_submissions').select('*').eq('id',body.application_id).eq('source_portal_id','aactivated').single(); if(!application)return out({error:'AACTIVATEDRX application not found'},404);
  const repCode=String(body.rep_code??'').replace(/[^A-Z0-9]/gi,'').toUpperCase(); if(!repCode)return out({error:'Representative code required'},400);
  let {data:rep}=await db.from('reps').select('id').eq('rep_slug',repCode).maybeSingle();
  const repPayload={rep_slug:repCode,rep_name:application.full_name,parent_rep_id:body.sponsor_rep_id||null,commission_rate:0};
  if(rep) await db.from('reps').update(repPayload).eq('id',rep.id); else {const created=await db.from('reps').insert(repPayload).select('id').single(); if(created.error)throw created.error; rep=created.data;}
  const {data:existingUsers}=await db.auth.admin.listUsers(); let authUser=existingUsers.users.find((candidate)=>candidate.email?.toLowerCase()===application.email.toLowerCase());
  if(!authUser){const created=await db.auth.admin.createUser({email:application.email,email_confirm:false,user_metadata:{full_name:application.full_name,role:'rep',brand_id:'aactivated'}});if(created.error)throw created.error;authUser=created.data.user;}
  await db.from('profiles').upsert({id:authUser.id,auth_user_id:authUser.id,email:application.email,full_name:application.full_name,phone:application.phone,role:'rep',brand_id:'aactivated',store_slug:'aactivated'},{onConflict:'id'});
  await db.from('reps').update({profile_id:authUser.id}).eq('id',rep.id);
  const {data:onboarding,error:onboardingError}=await db.from('aactivated_onboarding_profiles').upsert({application_id:application.id,rep_id:rep.id,user_id:authUser.id,state:'approved_onboarding_incomplete',account_status:'complete',commissions_enabled:false,referral_enabled:false,approved_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'application_id'}).select('id').single();if(onboardingError)throw onboardingError;
  await db.from('rep_store_intake_submissions').update({status:'ready_to_build',approval_status:'approved',approval_notes:body.internal_note||'Approved for secure onboarding',paypal_account:null}).eq('id',application.id);
  await notifyApproval(db,onboarding.id,application.email);
  await db.from('aactivated_onboarding_audit').insert({onboarding_id:onboarding.id,actor_id:user.id,action:'application_approved',reason:body.internal_note||null,metadata:{commission_configuration_pending:Number(body.commission_percent||0),existing_applicant_promoted:true}});
  return out({ok:true,onboarding_id:onboarding.id});
}catch(error){console.error('Secure approval failed',error instanceof Error?error.message:'unknown');return out({error:'Secure approval failed'},400);}});
function out(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors});}
async function notifyApproval(db:any,onboardingId:string,email:string){const path='/rep/onboarding';const {data:row,error}=await db.from('aactivated_onboarding_notifications').insert({onboarding_id:onboardingId,event_type:'application_approved',recipient_email:email,status:'pending',secure_portal_path:path}).select('id').single();if(error)throw error;if(!EMAIL_KEY){await db.from('aactivated_onboarding_notifications').update({status:'suppressed'}).eq('id',row.id);return;}try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${EMAIL_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:FROM_EMAIL,to:[email],subject:'Your AACTIVATEDRX representative application was approved',html:`<p>Your representative application was approved.</p><p>You may begin the secure onboarding steps now. Representative tools remain limited until final activation.</p><p><a href="${SITE}${path}">Continue AACTIVATEDRX onboarding</a></p>`})});await db.from('aactivated_onboarding_notifications').update({status:response.ok?'sent':'failed',sent_at:response.ok?new Date().toISOString():null}).eq('id',row.id);}catch{await db.from('aactivated_onboarding_notifications').update({status:'failed'}).eq('id',row.id);}}
