export const thePLoungeStorefront = {
  id: 'theplounge',
  slug: 'the-p-lounge',
  aliases: ['theplounge', 'p-lounge', 'plounge'],
  brandName: 'The P Lounge',
  ownerName: 'Kendra Salot',
  ownerEmail: 'hello@theplounge.com',
  ownerPhone: '909-915-9989',
  scopeCode: 'THEPLOUNGE',
  adminLabel: 'The P Lounge - Kendra Salot',
  storeType: 'platform_direct_whitelabel',
  commissionRate: 0.55,
  platformShare: 0.45,
  commissionType: 'net_profit_share',
  catalogSource: 'main',
  pricingSource: 'store_requested_prices',
  inventorySource: 'main',
  checkoutSource: 'main',
  assets: {
    logo: '/brands/the-p-lounge/the-p-lounge-logo.png',
    productPlaceholder: '/brands/the-p-lounge/the-p-lounge-vial.png',
    hero: '/brands/the-p-lounge/the-p-lounge-hero.png',
    lounge: '/brands/the-p-lounge/the-p-lounge-lounge.png',
    film: '/brands/the-p-lounge/the-p-lounge-film.mov',
  },
} as const;
