import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
/* eslint-disable @typescript-eslint/no-explicit-any -- Supabase Edge runtime client types are remote Deno imports. */
const URL=Deno.env.get('SUPABASE_URL')??'',ANON=Deno.env.get('SUPABASE_ANON_KEY')??'',SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')??'';
const EMAIL_KEY=Deno.env.get('EMAIL_PROVIDER_API_KEY')??Deno.env.get('RESEND_API_KEY')??'',FROM_EMAIL=Deno.env.get('FROM_EMAIL')??Deno.env.get('NOTIFY_FROM')??'PepScriptRX <noreply@pepscriptrx.com>',SITE=(Deno.env.get('SITE_URL')??Deno.env.get('APP_URL')??'https://pepscriptrx.vercel.app').replace(/\/+$/,'');
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Content-Type':'application/json'};
serve(async(req)=>{if(req.method==='OPTIONS')return out({});if(req.method!=='POST')return out({error:'Method not allowed'},405);try{
  const token=req.headers.get('Authorization')??'';const auth=createClient(URL,ANON,{global:{headers:{Authorization:token}}});const {data:{user}}=await auth.auth.getUser();if(!user)return out({error:'Authentication required'},401);
  const db=createClient(URL,SERVICE);const {data:profile}=await db.from('profiles').select('role,brand_id,store_slug').or(`id.eq.${user.id},auth_user_id.eq.${user.id}`).maybeSingle();const platform=['admin','owner','platform_admin','master_admin','super_admin'].includes(profile?.role);const scoped=['rx_plus_admin','partner_admin_full'].includes(profile?.role)&&['aactivated','aactivatedrx'].includes(String(profile?.brand_id??profile?.store_slug).toLowerCase());if(!platform&&!scoped)return out({error:'Administrator authorization required'},403);
  const body=await req.json();const action=String(body.action??'');
  if(action==='status_snapshot')return out(await statusSnapshot(db));
  if(action==='application_more_info'||action==='application_denied')await applicationDecision(db,user.id,body,action);
  else if(action==='w9_review')await reviewW9(db,auth,user.id,body);
  else if(action==='payout_review')await reviewPayout(db,auth,user.id,body);
  else if(action==='publish_agreement')await publishAgreement(db,user.id,body);
  else return out({error:'Unsupported action'},400);
  return out({ok:true});
}catch(error){console.error('Onboarding administration failed',error instanceof Error?error.message:'unknown');return out({error:'Administrative action failed'},400);}});
async function statusSnapshot(db:any){const [w,p]=await Promise.all([db.from('aactivated_w9_submissions').select('id,onboarding_id,status,tax_name,tin_last_four,created_at,correction_reason').order('created_at',{ascending:false}),db.from('aactivated_payout_profiles').select('id,onboarding_id,verification_status,masked_destination,submitted_at,admin_notes').is('superseded_at',null).order('submitted_at',{ascending:false})]);if(w.error||p.error)throw w.error??p.error;return {ok:true,w9s:w.data??[],payouts:p.data??[]};}
async function applicationDecision(db:any,actor:string,body:any,action:string){const note=clean(body.reason);if(note.length<10)throw new Error('A detailed reason is required');const denied=action==='application_denied';const {data:application,error}=await db.from('rep_store_intake_submissions').update({approval_status:denied?'rejected':'more_info_requested',status:denied?'rejected':'more_info_requested',approval_notes:note}).eq('id',body.application_id).eq('source_portal_id','aactivated').select('id,email').single();if(error)throw error;const {data:onboarding}=await db.from('aactivated_onboarding_profiles').update({state:denied?'application_declined':'application_more_info_required',updated_at:new Date().toISOString()}).eq('application_id',application.id).select('id').maybeSingle();await notify(db,onboarding?.id,denied?'application_denied':'application_more_info_requested',application.email,'/applicant');await audit(db,onboarding?.id,actor,action,note,{});}
async function reviewW9(db:any,auth:any,actor:string,body:any){const status=body.decision==='accept'?'accepted':'correction_required';const reason=clean(body.reason);if(status==='correction_required'&&reason.length<10)throw new Error('Correction reason required');const {data:row,error}=await db.from('aactivated_w9_submissions').update({status,reviewer_id:actor,reviewed_at:new Date().toISOString(),correction_reason:reason||null}).eq('id',body.submission_id).select('onboarding_id').single();if(error)throw error;const {error:profileError}=await db.from('aactivated_onboarding_profiles').update({w9_status:status,updated_at:new Date().toISOString()}).eq('id',row.onboarding_id);if(profileError)throw profileError;const {error:evaluationError}=await auth.rpc('evaluate_aactivated_onboarding',{p_onboarding_id:row.onboarding_id});if(evaluationError)throw evaluationError;await audit(db,row.onboarding_id,actor,`w9_${status}`,reason,{});}
async function reviewPayout(db:any,auth:any,actor:string,body:any){const status=body.decision==='verify'?'verified':'correction_required';const reason=clean(body.reason);if(status==='correction_required'&&reason.length<10)throw new Error('Correction reason required');const {data:row,error}=await db.from('aactivated_payout_profiles').update({verification_status:status,verified_at:status==='verified'?new Date().toISOString():null,admin_notes:reason||null}).eq('id',body.payout_id).select('onboarding_id').single();if(error)throw error;const {error:profileError}=await db.from('aactivated_onboarding_profiles').update({payout_status:status==='verified'?'complete':'correction_required',updated_at:new Date().toISOString()}).eq('id',row.onboarding_id);if(profileError)throw profileError;const {error:evaluationError}=await auth.rpc('evaluate_aactivated_onboarding',{p_onboarding_id:row.onboarding_id});if(evaluationError)throw evaluationError;await audit(db,row.onboarding_id,actor,`payout_${status}`,reason,{});}
async function publishAgreement(db:any,actor:string,body:any){const title=clean(body.title),version=clean(body.version),content=clean(body.content),companySignerName=clean(body.company_signer_name),companySignatureText=clean(body.company_signature_text);if(!body.legal_approval_confirmed||!body.company_signature_confirmed||title.length<5||version.length<1||content.length<100||companySignerName.length<2||companySignatureText.length<2)throw new Error('Approved agreement details, company authorization, and electronic signature are required');await db.from('aactivated_agreements').update({status:'retired'}).eq('brand_id','aactivated').eq('status','approved');const hash=await sha256(content);const signedAt=new Date().toISOString();const {error}=await db.from('aactivated_agreements').insert({brand_id:'aactivated',title,version,effective_date:body.effective_date,content,content_hash:hash,status:'approved',created_by:actor,approved_by:actor,published_at:signedAt,company_signed_by:actor,company_signer_name:companySignerName,company_signature_text:companySignatureText,company_signed_at:signedAt});if(error)throw error;await audit(db,null,actor,'agreement_published',null,{version,content_hash:hash,company_signer_name:companySignerName,company_signed:true});}
async function notify(db:any,onboarding:string|undefined,event:string,email:string,path:string){if(!onboarding)return;const {data:row,error}=await db.from('aactivated_onboarding_notifications').insert({onboarding_id:onboarding,event_type:event,recipient_email:email,status:'pending',secure_portal_path:path}).select('id').single();if(error)throw error;if(!EMAIL_KEY){await db.from('aactivated_onboarding_notifications').update({status:'suppressed'}).eq('id',row.id);return;}const subject=event==='application_denied'?'AACTIVATEDRX application update':event==='application_more_info_requested'?'AACTIVATEDRX needs more information':'AACTIVATEDRX onboarding update';const message=event==='application_more_info_requested'?'Additional information is needed to continue reviewing your representative application.':event==='application_denied'?'A decision has been recorded for your representative application.':'Your representative onboarding status has been updated.';try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${EMAIL_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:FROM_EMAIL,to:[email],subject,html:`<p>${message}</p><p><a href="${SITE}${path}">Open your secure AACTIVATEDRX portal</a></p>`})});await db.from('aactivated_onboarding_notifications').update({status:response.ok?'sent':'failed',sent_at:response.ok?new Date().toISOString():null}).eq('id',row.id);}catch{await db.from('aactivated_onboarding_notifications').update({status:'failed'}).eq('id',row.id);}}
async function audit(db:any,onboarding:string|null|undefined,actor:string,action:string,reason:string|null,metadata:unknown){await db.from('aactivated_onboarding_audit').insert({onboarding_id:onboarding??null,actor_id:actor,action,reason:reason||null,metadata});}
const clean=(v:unknown)=>String(v??'').trim();async function sha256(v:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))).map(b=>b.toString(16).padStart(2,'0')).join('');}function out(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors});}
