import { useEffect, useState } from 'react';
import DashLayout from '../../components/layout/DashLayout';
import { supabase } from '../../lib/supabase';

type Row = { id: string; state: string; account_status: string; agreement_status: string; w9_status: string; starter_kit_status: string; payout_status: string; approved_at: string | null; activated_at: string | null; last_activity_at: string; application?: { full_name?: string; email?: string; referral_rep?: string; approval_status?: string } | null };

export default function AdminAactivatedOnboarding() {
  const [rows, setRows] = useState<Row[]>([]); const [error, setError] = useState('');
  async function load() { const { data, error: loadError } = await supabase!.from('aactivated_onboarding_profiles').select('id,state,account_status,agreement_status,w9_status,starter_kit_status,payout_status,approved_at,activated_at,last_activity_at,application:rep_store_intake_submissions(full_name,email,referral_rep,approval_status)').eq('brand_id','aactivated').order('last_activity_at',{ ascending:false }); if (loadError) setError(loadError.message); else setRows((data ?? []) as unknown as Row[]); }
  useEffect(() => { void load(); }, []);
  async function activate(id: string) { setError(''); const { error: actionError } = await supabase!.rpc('activate_aactivated_onboarding',{ p_onboarding_id:id }); if (actionError) setError(actionError.message); await load(); }
  async function override(id: string) { const reason = window.prompt('Enter the business-approved override reason (minimum 10 characters).'); if (!reason || reason.trim().length < 10) return; const { data: { user } } = await supabase!.auth.getUser(); if (!user) return; const { error: actionError } = await supabase!.from('aactivated_onboarding_overrides').insert({ onboarding_id:id, step:'activation', reason:reason.trim(), authorized_by:user.id }); if (actionError) setError(actionError.message); else await supabase!.from('aactivated_onboarding_audit').insert({ onboarding_id:id, actor_id:user.id, action:'activation_override_created', reason:reason.trim() }); await load(); }
  function exportReport() { const header='Name,Email,Application,Account,Agreement,W9,Starter Kit,Payout,State,Last Activity\n'; const body=rows.map((row)=>[row.application?.full_name,row.application?.email,row.application?.approval_status,row.account_status,row.agreement_status,row.w9_status,row.starter_kit_status,row.payout_status,row.state,row.last_activity_at].map(csv).join(',')).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([header+body],{type:'text/csv'})); a.download='aactivated-onboarding-nonsensitive.csv'; a.click(); URL.revokeObjectURL(a.href); }
  return <DashLayout role="admin"><div><div style={{ display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap' }}><div><p className="eyebrow">AACTIVATEDRX administration</p><h1>Rep Onboarding Manager</h1><p>Brand-scoped onboarding status. Sensitive tax and payout values are excluded.</p></div><button className="btn btn-secondary" onClick={exportReport}>Export non-sensitive report</button></div>{error&&<div className="alert alert-error">{error}</div>}<div style={{ overflowX:'auto' }}><table className="data-table"><thead><tr><th>Rep</th><th>Application</th><th>Account</th><th>Agreement</th><th>W-9</th><th>Starter kit</th><th>Payout</th><th>Overall</th><th>Last activity</th><th>Actions</th></tr></thead><tbody>{rows.map((row)=><tr key={row.id}><td><strong>{row.application?.full_name??'Pending rep'}</strong><br/><small>{row.application?.email}</small></td><td>{row.application?.approval_status}</td><td>{row.account_status}</td><td>{row.agreement_status}</td><td>{row.w9_status}</td><td>{row.starter_kit_status}</td><td>{row.payout_status}</td><td>{row.state}</td><td>{new Date(row.last_activity_at).toLocaleDateString()}</td><td><button className="btn btn-primary btn-sm" onClick={()=>void activate(row.id)}>Verify & activate</button> <button className="btn btn-secondary btn-sm" onClick={()=>void override(row.id)}>Override</button></td></tr>)}</tbody></table></div></div></DashLayout>;
}
function csv(value: unknown){return `"${String(value??'').replaceAll('"','""')}"`;}
