export const ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Analytics', path: '/admin/analytics', icon: '03' },
  { label: 'Products', path: '/admin/products', icon: '04' },
  { label: 'Inventory', path: '/admin/inventory', icon: '05' },
  { label: 'Product Intelligence', path: '/admin/operations/product-intelligence', icon: '06' },
  { label: 'Rx+', path: '/admin/rx-plus', icon: '07' },
  { label: 'Promo Links', path: '/admin/aactivated-promos', icon: '08' },
  { label: 'Leads', path: '/admin/leads', icon: '09' },
  { label: 'Zelle Payments', path: '/admin/zelle-payments', icon: '10' },
  { label: 'Rep Requests', path: '/admin/rep-requests', icon: '11' },
  { label: 'Reps', path: '/admin/reps', icon: '12' },
  { label: 'Rep Store Manager', path: '/admin/rep-store-manager', icon: '13' },
  { label: 'Commission Center', path: '/admin/commission-center', icon: '14' },
  { label: 'Product Lists', path: '/admin/product-lists', icon: '15' },
  { label: 'Pricing Manager', path: '/admin/pricing', icon: '16' },
  { label: 'Payouts', path: '/admin/payouts', icon: '17' },
  { label: 'Scope Codes', path: '/admin/scope-codes', icon: '18' },
  { label: 'PayPal Audit', path: '/admin/payment-audit', icon: '19' },
  { label: 'Fulfillment', path: '/admin/fulfillment', icon: '20' },
  { label: 'Rep Performance', path: '/admin/rep-performance', icon: '21' },
  { label: 'Customer Activity', path: '/admin/customer-activity', icon: '22' },
  { label: 'Product Performance', path: '/admin/product-performance', icon: '23' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '24' },
  { label: 'Feature Requests', path: '/admin/feature-requests', icon: '25' },
];

export const RX_PLUS_ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Rep Requests', path: '/admin/rep-requests', icon: '03' },
  { label: 'Reps', path: '/admin/reps', icon: '04' },
  { label: 'Rep Store Manager', path: '/admin/rep-store-manager', icon: '05' },
  { label: 'Commission Center', path: '/admin/commission-center', icon: '06' },
  { label: 'Product Lists', path: '/admin/product-lists', icon: '07' },
  { label: 'Pricing Manager', path: '/admin/pricing', icon: '08' },
  { label: 'Products', path: '/admin/products', icon: '09' },
  { label: 'Customer Activity', path: '/admin/customer-activity', icon: '10' },
  { label: 'Product Performance', path: '/admin/product-performance', icon: '11' },
  { label: 'Promo Links', path: '/admin/aactivated-promos', icon: '12' },
  { label: 'Leads', path: '/admin/leads', icon: '13' },
  { label: 'Payouts', path: '/admin/payouts', icon: '14' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '15' },
  { label: 'Feature Requests', path: '/admin/feature-requests', icon: '16' },
];
