import { useEffect,useState,type FormEvent } from 'react';
import DashLayout from '../../components/layout/DashLayout';
import { supabase } from '../../lib/supabase';

type Row={id:string;state:string;account_status:string;agreement_status:string;w9_status:string;starter_kit_status:string;payout_status:string;approved_at:string|null;activated_at:string|null;last_activity_at:string;application?:{id?:string;full_name?:string;email?:string;referral_rep?:string;approval_status?:string}|null};
type W9={id:string;onboarding_id:string;status:string;tax_name:string;tin_last_four:string;created_at:string;correction_reason:string|null};
type Payout={id:string;onboarding_id:string;verification_status:string;masked_destination:string;submitted_at:string;admin_notes:string|null};
export default function AdminAactivatedOnboarding(){const [rows,setRows]=useState<Row[]>([]),[w9s,setW9s]=useState<W9[]>([]),[payouts,setPayouts]=useState<Payout[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState('');
  async function load(){const [r,snapshot]=await Promise.all([supabase!.from('aactivated_onboarding_profiles').select('id,state,account_status,agreement_status,w9_status,starter_kit_status,payout_status,approved_at,activated_at,last_activity_at,application:rep_store_intake_submissions(id,full_name,email,referral_rep,approval_status)').eq('brand_id','aactivated').order('last_activity_at',{ascending:false}),supabase!.functions.invoke('manage-aactivated-onboarding',{body:{action:'status_snapshot'}})]);const failure=r.error||snapshot.error;if(failure)setError(failure.message);else{setRows((r.data??[]) as unknown as Row[]);setW9s((snapshot.data?.w9s??[]) as W9[]);setPayouts((snapshot.data?.payouts??[]) as Payout[]);}}
  useEffect(()=>{void load();},[]);
  async function invoke(name:string,body:Record<string,unknown>,key:string){setSaving(key);setError('');setMessage('');const {data,error:fnError}=await supabase!.functions.invoke(name,{body});setSaving('');if(fnError||data?.error){setError(String(data?.error||fnError?.message||'Action failed'));return false;}setMessage('Administrative action completed and recorded.');await load();return true;}
  async function approve(row:Row){const code=window.prompt('Representative code (letters and numbers only):');if(!code||!row.application?.id)return;const note=window.prompt('Internal approval note:')||'Approved for secure onboarding';await invoke('approve-aactivated-onboarding',{application_id:row.application.id,rep_code:code,internal_note:note},`approve-${row.id}`);}
  async function decision(row:Row,action:'application_more_info'|'application_denied'){if(!row.application?.id)return;const reason=window.prompt(action==='application_denied'?'Enter denial reason (minimum 10 characters):':'Describe the additional information required (minimum 10 characters):');if(!reason||reason.trim().length<10)return;await invoke('manage-aactivated-onboarding',{action,application_id:row.application.id,reason},`${action}-${row.id}`);}
  async function review(kind:'w9'|'payout',id:string,decision:string,onboarding:string){const correction=!['accept','verify'].includes(decision);const reason=correction?window.prompt('Enter correction instructions (minimum 10 characters):')||'':'';if(correction&&reason.trim().length<10)return;await invoke('manage-aactivated-onboarding',{action:`${kind}_review`,[kind==='w9'?'submission_id':'payout_id']:id,decision,reason},`${kind}-${onboarding}`);}
  async function activate(id:string){setSaving(`activate-${id}`);setError('');const {error:actionError}=await supabase!.rpc('activate_aactivated_onboarding',{p_onboarding_id:id});setSaving('');if(actionError)setError(actionError.message);else setMessage('Representative portal activated.');await load();}
  function exportReport(){const header='Name,Email,Application,Account,Agreement,W9,Starter Kit,Payout,State,Last Activity\n';const body=rows.map(row=>[row.application?.full_name,row.application?.email,row.application?.approval_status,row.account_status,row.agreement_status,row.w9_status,row.starter_kit_status,row.payout_status,row.state,row.last_activity_at].map(csv).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([header+body],{type:'text/csv'}));a.download='aactivated-onboarding-nonsensitive.csv';a.click();URL.revokeObjectURL(a.href);}
  return <DashLayout role="admin"><div style={{display:'grid',gap:18}}><div style={{display:'flex',justifyContent:'space-between',gap:16,flexWrap:'wrap'}}><div><p className="eyebrow">AACTIVATEDRX administration</p><h1>Rep Onboarding Manager</h1><p>Application decisions, compliance review, and final activation. Sensitive values remain masked.</p></div><button className="btn btn-secondary" onClick={exportReport}>Export non-sensitive report</button></div>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-success">{message}</div>}<AgreementPublisher invoke={invoke}/><div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Rep</th><th>Application</th><th>Agreement</th><th>W-9 review</th><th>Starter kit</th><th>Payout review</th><th>Overall</th><th>Actions</th></tr></thead><tbody>{rows.map(row=>{const w9=w9s.find(item=>item.onboarding_id===row.id),payout=payouts.find(item=>item.onboarding_id===row.id);return <tr key={row.id}><td><strong>{row.application?.full_name??'Pending rep'}</strong><br/><small>{row.application?.email}</small></td><td>{row.application?.approval_status||'pending'}</td><td>{row.agreement_status}</td><td>{w9?<><strong>{w9.status}</strong><br/><small>{w9.tax_name} · TIN ••••{w9.tin_last_four}</small>{w9.status==='submitted'&&<div><button className="btn btn-primary btn-sm" onClick={()=>void review('w9',w9.id,'accept',row.id)}>Accept</button> <button className="btn btn-secondary btn-sm" onClick={()=>void review('w9',w9.id,'correct',row.id)}>Correct</button></div>}</>:'not submitted'}</td><td>{row.starter_kit_status}</td><td>{payout?<><strong>{payout.verification_status}</strong><br/><small>{payout.masked_destination}</small>{payout.verification_status==='submitted'&&<div><button className="btn btn-primary btn-sm" onClick={()=>void review('payout',payout.id,'verify',row.id)}>Verify</button> <button className="btn btn-secondary btn-sm" onClick={()=>void review('payout',payout.id,'correct',row.id)}>Correct</button></div>}</>:'not submitted'}</td><td>{row.state}</td><td style={{minWidth:230}}>{row.application?.approval_status!=='approved'&&<><button className="btn btn-primary btn-sm" disabled={Boolean(saving)} onClick={()=>void approve(row)}>Approve</button> <button className="btn btn-secondary btn-sm" onClick={()=>void decision(row,'application_more_info')}>More info</button> <button className="btn btn-danger btn-sm" onClick={()=>void decision(row,'application_denied')}>Deny</button></>} {row.application?.approval_status==='approved'&&<button className="btn btn-primary btn-sm" disabled={Boolean(saving)||row.state==='active'} onClick={()=>void activate(row.id)}>{row.state==='active'?'Active':'Verify & activate'}</button>}</td></tr>})}</tbody></table></div></div></DashLayout>;
}
function AgreementPublisher({invoke}:{invoke:(name:string,body:Record<string,unknown>,key:string)=>Promise<boolean>}){const [open,setOpen]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);const ok=await invoke('manage-aactivated-onboarding',{action:'publish_agreement',title:data.get('title'),version:data.get('version'),effective_date:data.get('effective_date'),content:data.get('content'),legal_approval_confirmed:data.has('legal_approval_confirmed')},'agreement');if(ok){form.reset();setOpen(false);}}return <div className="card" style={{padding:18}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><strong>Rep agreement publication</strong><p>Only publish text that has completed legal approval.</p></div><button className="btn btn-secondary" onClick={()=>setOpen(!open)}>{open?'Cancel':'Publish approved agreement'}</button></div>{open&&<form onSubmit={submit} style={{display:'grid',gap:10}}><input className="form-input" name="title" placeholder="Agreement title" required/><div className="form-grid-2"><input className="form-input" name="version" placeholder="Version" required/><input className="form-input" name="effective_date" type="date" required/></div><textarea className="form-textarea" name="content" rows={12} minLength={100} placeholder="Paste the complete legally approved agreement" required/><label><input name="legal_approval_confirmed" type="checkbox" required/> I confirm this exact agreement text has legal approval for staging publication.</label><button className="btn btn-primary">Publish versioned agreement</button></form>}</div>}
function csv(value:unknown){return `"${String(value??'').replaceAll('"','""')}"`;}
