export const ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Analytics', path: '/admin/analytics', icon: '03' },
  { label: 'Executive Diligence', path: '/admin/executive-diligence', icon: 'DD' },
  { label: 'Products', path: '/admin/products', icon: '04' },
  { label: 'Inventory', path: '/admin/inventory', icon: '05' },
  { label: 'Product Intelligence', path: '/admin/operations/product-intelligence', icon: '06' },
  { label: 'Rx+', path: '/admin/rx-plus', icon: '07' },
  { label: 'Discount Codes', path: '/admin/aactivated-promos', icon: '08' },
  { label: 'Leads', path: '/admin/leads', icon: '09' },
  { label: 'Manual Payments', path: '/admin/zelle-payments', icon: '10' },
  { label: 'Rep Requests', path: '/admin/rep-requests', icon: '11' },
  { label: 'Reps', path: '/admin/reps', icon: '12' },
  { label: 'Rep Store Manager', path: '/admin/rep-store-manager', icon: '13' },
  { label: 'Rep Starter Kits', path: '/admin/aactivated-starter-kits', icon: '14' },
  { label: 'Commission Center', path: '/admin/commission-center', icon: '15' },
  { label: 'Product Lists', path: '/admin/product-lists', icon: '16' },
  { label: 'Pricing Manager', path: '/admin/pricing', icon: '17' },
  { label: 'Payouts', path: '/admin/payouts', icon: '18' },
  { label: 'Scope Codes', path: '/admin/scope-codes', icon: '19' },
  { label: 'PayPal Audit', path: '/admin/payment-audit', icon: '20' },
  { label: 'Fulfillment', path: '/admin/fulfillment', icon: '21' },
  { label: 'Rep Performance', path: '/admin/rep-performance', icon: '22' },
  { label: 'Customer Activity', path: '/admin/customer-activity', icon: '23' },
  { label: 'Product Performance', path: '/admin/product-performance', icon: '24' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '25' },
  { label: 'Feature Requests', path: '/admin/feature-requests', icon: '26' },
  { label: 'Marketing Assets', path: '/admin/marketing-assets', icon: '27' },
];

export const RX_PLUS_ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Rep Requests', path: '/admin/rep-requests', icon: '03' },
  { label: 'Reps', path: '/admin/reps', icon: '04' },
  { label: 'Rep Store Manager', path: '/admin/rep-store-manager', icon: '05' },
  { label: 'Rep Starter Kits', path: '/admin/aactivated-starter-kits', icon: '06' },
  { label: 'Commission Center', path: '/admin/commission-center', icon: '07' },
  { label: 'Product Lists', path: '/admin/product-lists', icon: '08' },
  { label: 'Storefront Products', path: '/admin/products', icon: '09' },
  { label: 'Customer Activity', path: '/admin/customer-activity', icon: '10' },
  { label: 'Product Performance', path: '/admin/product-performance', icon: '11' },
  { label: 'Discount Codes', path: '/admin/aactivated-promos', icon: '12' },
  { label: 'Leads', path: '/admin/leads', icon: '13' },
  { label: 'Payouts', path: '/admin/payouts', icon: '14' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '15' },
  { label: 'Feature Requests', path: '/admin/feature-requests', icon: '16' },
  { label: 'Marketing Assets', path: '/admin/marketing-assets', icon: '17' },
];

export const PARTNER_LIMITED_ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Customers', path: '/admin/leads', icon: '03' },
  { label: 'Reps', path: '/admin/reps', icon: '04' },
  { label: 'Payouts', path: '/admin/payouts', icon: '05' },
  { label: 'Marketing Assets', path: '/admin/marketing-assets', icon: '06' },
];

export const VITALITY_ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Customers', path: '/admin/leads', icon: '03' },
  { label: 'Analytics', path: '/admin/analytics', icon: '04' },
  { label: 'Products', path: '/admin/products', icon: '05' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '06' },
  { label: 'Marketing Assets', path: '/admin/marketing-assets', icon: '07' },
];

export const SANDMAN_ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Customers', path: '/admin/leads', icon: '03' },
  { label: 'Pricing Manager', path: '/admin/pricing', icon: '04' },
  { label: 'Discount Codes', path: '/admin/aactivated-promos', icon: '05' },
  { label: 'Product Visibility', path: '/admin/products', icon: '06' },
  { label: 'Analytics', path: '/admin/analytics', icon: '07' },
  { label: 'Sales Reports', path: '/admin/commission-center', icon: '08' },
  { label: 'Rep Management', path: '/admin/reps', icon: '09' },
  { label: 'Inventory', path: '/admin/inventory', icon: '10' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '11' },
  { label: 'Marketing Assets', path: '/admin/marketing-assets', icon: '12' },
];

export const BLACKLINE_ADMIN_NAV = [
  { label: 'Dashboard', path: '/admin', icon: '01' },
  { label: 'Orders', path: '/admin/submissions', icon: '02' },
  { label: 'Customers', path: '/admin/leads', icon: '03' },
  { label: 'Pricing Manager', path: '/admin/pricing', icon: '04' },
  { label: 'Discount Codes', path: '/admin/aactivated-promos', icon: '05' },
  { label: 'Product Visibility', path: '/admin/products', icon: '06' },
  { label: 'Analytics', path: '/admin/analytics', icon: '07' },
  { label: 'Sales Reports', path: '/admin/commission-center', icon: '08' },
  { label: 'Rep Management', path: '/admin/reps', icon: '09' },
  { label: 'Inventory', path: '/admin/inventory', icon: '10' },
  { label: 'Store Settings', path: '/admin/store-settings', icon: '11' },
  { label: 'Marketing Assets', path: '/admin/marketing-assets', icon: '12' },
];
